server:
  port: 8022
  ssl:
    enabled: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  application:
    name: application2
    default-domain: application22
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false

endpoints:
  jmx:
    enabled: false
    domain: application22
  env:
    enabled: false


eureka:
  server:
    port: 8000
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${eureka.server.port}/eureka
  instance:
    metadataMap:
      instanceId: application22
      zone: zone2
      version: 2.0.0
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3
ribbon:
  extensions:
    propagation:
      keys:
        - version
        - zone
    rule:
      strict-matcher:
        enabled: false
      favorite-zone:
        enabled: true
        entryKey: zone

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false