server:
  port: 8001
  ssl:
    enabled: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  application:
    name: zuul
    default-domain: zuul
  cloud:
    config:
      enabled: false
  jmx:
    enabled: false

endpoints:
  enabled: false
  jmx:
    enabled: false
    domain: zuul
  env:
    enabled: false

eureka:
  server:
    port: 8000
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${eureka.server.port}/eureka
  instance:
    metadataMap:
      instanceId: zuul
      zone: zone1
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 3

ribbon:
  eager-load:
    enabled: true
    clients:
      - service1
      - service2
  extensions:
    propagation:
      keys:
        - version
        - favorite-zone
        - upstream-zone

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  addProxyHeaders: true
  addHostHeader: true
  routes:
    service1:
      serviceId: service1
      path: /service1/**
      stripPrefix: false
    service2:
      serviceId: service2
      path: /service2/**
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false